name: ci-customMessage
on: push
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v3

      - name: Run Cypress tests 🧪
        # https://github.com/cypress-io/github-action
        uses: cypress-io/github-action@v5
        with:
          command: |
            npx cypress-expect run --config-file cypress.customMessage.config.js \
              --record --tag custom --expect-exactly cypress/expected.json
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          DEBUG: cypress-slack-notify

      - name: Print JSON log 🖨
        run: cat cypress-slack-notified.json

      - name: Check JSON log ✅
        run: node ./test-logs/ci.customMessage.js
